
name: "Removing lock file"

on:
  schedule:
  - cron: "0 2 * * 0-6"

jobs:
  remove:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v1
      - name: Remove File
        uses: JesseTG/rm@v1.0.0
        with:
          path: .project-lock.json

